Form_Builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Form_Builder import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('account.urls','accounts'),namespace='account')),
    path('core/', include(('core.urls','core'),namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
    path('staff-list/',ListAllStaffView.as_view(), name='staff-list'),
    path('staff-add/',AddStaffView.as_view(), name='staff-add'),
    path('staff-update/<int:id>/',UpdateStaff.as_view(), name='staff-update'),
    path('staff-delete/<int:id>/',DeleteStaffPerson.as_view(), name='staff-delete'),
    
    path('user-list/',ListAllUserView.as_view(), name='user-list'),
    path('user-add/',AddUserView.as_view(), name='user-add'),
    path('user-update/<int:id>/',UpdateUserView.as_view(), name='user-update'),
    path('user-delete/<int:id>/',DeleteUserPerson.as_view(), name='user-delete'),
    
    path('company-list/', CompanyListView.as_view(), name="company-list"),
    path('company-add/', AddCompanyView.as_view(), name="company-add"),
    path('company-update/<int:id>/', UpdateCompanyView.as_view(), name="company-update"),
    path('company-delete/<int:id>/',DeleteCompany.as_view(), name='company-delete'),
    # path('companypanel/',CompanypanelView.as_view(), name='companypanel'),
    path('update-status-approve/<int:id>/',UpdateStatusApproveView, name='update-status-approve'),
    path('update-status-reject/<int:id>/',UpdateStatusRejectView, name='update-status-reject'),
    path('company_register/', CompanyRegisterView.as_view(), name="company_register"),
    
    path("NotPageFound", NotPageFound ,name="NotPageFound"),
] 

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from Form_Builder import settings
from .views import *

urlpatterns = [
    path('', HomeView, name='home'),
    path('BuildForm/', BuildFormView, name='BuildForm'),
    path('saveForm/', saveForm, name='saveForm'),
    path('saveFormData/', saveFormData, name='saveFormData'),
    path('form/<str:form_uid>', generate_random_link, name='linkgenerator'),
    path('published_form/', PublishFormView.as_view(), name="published_form"),
    path('filledform_list/', FilledFormListView.as_view(), name="filledform_list"),
    path('publishedform_delete/<int:id>/', DeletePublishedForm.as_view(), name="publishedform_delete"),
    path('filledform_delete/<int:id>/', DeleteFilledForm.as_view(), name="filledform_delete"),
    
] 

core/models.py
import uuid
from django.db import models
from account.models import *
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class FormAttributes(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    # form_uid = models.UUIDField(default= uuid.uuid4, null=True, blank=True)
    form_uid = models.CharField(max_length=255, null=True, blank=True)
    form_name = models.CharField(max_length=255, null=True, blank=True)
    form_link = models.CharField(max_length=255, null=True, blank=True)
    form_qrcode = models.TextField(null=True, blank=True)
    attributes = models.TextField()
    
    def __str__(self):
        return str(self.form_uid)

class FormValues(models.Model):
    
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
    FormName = models.CharField(max_length=255, null=True, blank=True)
    FormID = models.ForeignKey(FormAttributes, on_delete=models.CASCADE, null=True, blank=True)
    FormValue = models.TextField()
    
    def __str__(self):
        return str(self.FormName)

core/views.py
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from account.forms import LoginForm
from core.models import *
from django.contrib import messages
from django.views.generic import TemplateView,View
import uuid
import json
import png
import pyshorteners
import pyqrcode

User = get_user_model()

def HomeView(request):
    context={}
    user = request.user.id
    
    context['approvedcompanies'] = Company.objects.all().filter(is_status = True).count()
    context['pendingapprovecompanies'] = Company.objects.all().filter(is_status = False).count()
    context['total_staff'] = User.objects.all().filter(type = "STAFF").count()
    context['total_user'] = User.objects.all().filter(type = "USER").count()
    context['company_user'] = User.objects.all().filter(type="USER" , created_by = user).count()
    context['company_staff'] = User.objects.all().filter(type="STAFF" , created_by = user).count()
    context['staff_user'] = User.objects.all().filter(type="USER" , created_by = user).count()
    context['form'] = FormAttributes.objects.all().count()
    context['user_form'] = FormAttributes.objects.all().filter(user = user).count()
    print(context)
    return render(request,'core/home.html',context)
    
    
def BuildFormView(request, *args, **kwargs):
    return render(request, 'core/Build_form.html')

def saveForm(request, *args, **kwargs):

    user = request.user

    random_uuid = uuid.uuid4()

    link_shorter = pyshorteners.Shortener()
    generated_link = link_shorter.tinyurl.short(f"127.0.0.1:8000/core/form/{random_uuid}")

    # print("Generated link: ", generated_link)
    url = pyqrcode.create(generated_link)
    
    generated_qrcode = url.png_as_base64_str(scale=5)

    context = {
        "attribute":request.POST['tab_list'],
        "form_name" : request.POST['formname'],
    }
    
    Attributes = FormAttributes(
        user = user,
        form_uid = random_uuid,
        form_name = context['form_name'],
        form_link = generated_link,
        form_qrcode = generated_qrcode,
        attributes = context['attribute'],
    )
    
    if Attributes:
        Attributes.save()
        messages.success(request, "Save form attributes successfully...")
    else:
        messages.error(request, "Somethings want wrong...")

    # context["messages"] = messages
    return JsonResponse(context, safe=True)

def saveFormData(request, *args, **kwargs):

    user = request.user
    if user.is_authenticated:
        context = {
            "attribute":request.POST['tab_list'], 
            "uuid":request.POST['uuId'],
            "form_name": request.POST['form_name'],
        }
        form_attributes = get_object_or_404(FormAttributes, form_uid= context['uuid'])

        Attributes = FormValues(
            user = user,
            FormID = form_attributes,
            FormName = context['form_name'],
            FormValue = context['attribute']
        )
        if Attributes:
            Attributes.save()
            messages.success(request, "Save form attributes successfully...")
        else:
            messages.error(request, "Somethings want wrong...")

        return JsonResponse(context, safe=True)
    else:
        context = {
            "attribute":request.POST['tab_list'], 
            "uuid":request.POST['uuId'],
            "form_name": request.POST['form_name'],
        }
        form_attributes = get_object_or_404(FormAttributes, form_uid= context['uuid'])

        Attributes = FormValues(
            FormID = form_attributes,
            FormName = context['form_name'],
            FormValue = context['attribute']
        )
        if Attributes:
            Attributes.save()
            messages.success(request, "Save form attributes successfully...")
        else:
            messages.error(request, "Somethings want wrong...")

        return JsonResponse(context, safe=True)


def generate_random_link(request, form_uid):

    context  = {}
    
    form = LoginForm(request.POST or None)
    
    form_data = FormAttributes.objects.get(form_uid=form_uid)
    print(form_data.form_link)

    form_uuid = form_data.form_uid
    data = eval(form_data.attributes)
    
    json_string = json.dumps(data, indent=4)

    context['uuid'] = form_uuid
    context['attribute'] = json_string
    context['form_data'] = form_data
    context['form'] = form

    return render(request, 'core/Fill_form.html', context)

class DeletePublishedForm(View):
    
    def get(self, request, id):
        context = {}
        published_form = FormAttributes.objects.get(pk=id)
        if published_form.delete():
            messages.success(request,"Form SuccessFully Deleted....")
            return redirect('core:published_form')
        else:
            messages.warning(request, "Something wen't Wrong...!" )
        context['published_form'] = published_form
        return render(request, 'core/published_form.html', context)
    
    def post(self, request):
        ...
        
class DeleteFilledForm(View):
    
    def get(self, request, id):
        context = {}
        value_form = FormValues.objects.get(pk=id)
        if value_form.delete():
            messages.success(request,"Form SuccessFully Deleted....")
            return redirect('core:Filledform_list')
        else:
            messages.warning(request, "Something wen't Wrong...!" )
        context['value_form'] = value_form
        return render(request, 'core/Filledform_list.html', context)
    
    def post(self, request):
        ...

class PublishFormView(TemplateView):

    def get(self,request):
        if request.user.is_superuser:
            users = FormAttributes.objects.all()
        else:
            user = request.user.id
            users = FormAttributes.objects.filter(user = user) 
        context={
            "users" : users
        }
        return render(request, "core/published_form.html",context)

class FilledFormListView(TemplateView):

    def get(self,request):
        user = request.user
        if request.user.is_superuser:
            fm_value = FormValues.objects.all()
        elif user.type == "COMPANY":
            cmp_users = CustomUser.objects.filter(created_by=user.id, type="USER")
            fm_value = FormValues.objects.filter(user__in=cmp_users)
            print(fm_value)
        elif user.type == "STAFF":
            cmp_users = CustomUser.objects.filter(created_by=user.id, type="USER")
            fm_value = FormValues.objects.filter(user__in=cmp_users)
            print(fm_value)
            
        else:
            fm_value = FormValues.objects.filter(user = user) 
        
        context={
            "fm_value" : fm_value
        }
        return render(request, "core/Filledform_list.html", context)
    
    def post(self, request):
        ...

templates/core/Fill_form.html
{% extends "base.html" %}

{% block title %}
Fill Form
{% endblock title %}

{% block content %}

<!-- Alert Start -->
{% block error_messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-sticky alert-{{ message.tags }}" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-hidden="true">×</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}
{% endblock error_messages %}
<!-- Alert End -->

<div class="page-header">
    <h1 class="page-title" id="form_name">{{ form_data.form_name }}</h1>
    <div>
    </div>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
        <form method="post">
            {% csrf_token %}
            <div class="card card-headpills">
                <div class="card-header border-bottom">
                    <div class="card-title">
                        <ul class="nav nav-pills card-header-pills" id="nav-tab">
                            <!-- <li class="nav-item px-2 mb-2">
                                <a class="btn btn-outline-primary active" style="width: 93px;" data-bs-toggle="tab" href="#activepills">Home</a>
                            </li> -->
                            
                        </ul>
                    </div>
                    <div class="card-options">
                        <!-- <button class="btn btn-outline-primary mx-2" type="button" id="add_tab_content">+</button> -->
                    </div>
                </div>
                <div class="card-body">
                    <div id="attribute" hidden>{{ attribute }}</div>
                    <div class="tab-content" id="nav-tabContent" >
                        <!-- <div class="tab-pane active dropArea box2 nav-home border tabpen_min_hight" id="activepills">
                            
                        </div> -->
                    </div>
                </div>
                <div class="card-footer text-end px-2">
                    <button type="submit" class="btn btn-danger" id="reset">Clear Form</button>
                    <button type="submit" class="btn btn-success" id="save">SAVE</button>
                </div>
            </div>
        </form>
    </div>
</div>


 <!-- Inout modal -->
 <div class="modal fade" id="input-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h5 class="modal-title">Log In To Continue..</h5>
                <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'accounts:login' %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="text" class="form-control" name="current_url" value="{{ request.path }}" hidden>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Email Address</label>
                        {{ form.email }}
                        {% comment %} <input type="text" class="form-control" id="recipient-name"> {% endcomment %}
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Password</label>
                        {{ form.password }}
                        {% comment %} <input type="text" class="form-control" id="recipient-name"> {% endcomment %}
                    </div>
                    <button class="btn ripple btn-success" type="submit">Log In</button>
                    <button class="btn ripple btn-warning" data-bs-dismiss="modal" type="button">Proceed WithOut LogIn</button>
                </form>
            </div>
            {% comment %} <div class="modal-footer">
                <button class="btn ripple btn-success" type="button">Save changes</button>
            </div> {% endcomment %}
        </div>
    </div>
</div>
<!-- End Datepicker modal -->


{% endblock content %}

{% block extrajs %}

{% if request.user.is_authenticated %}
  
{% else %}
<script>
    $(window).on('load', function() {
        $('#input-modal').modal('show');
    });
</script>
{% endif %}

<script>    

    var jsonString = document.getElementById("attribute").textContent;
    var form = document.createElement('div');
    // var frame = document.getElementById('boxcontent').appendChild(form);
    // var divElement = frame.appendChild(document.createElement('div'));
    var tab_frame = document.getElementById('nav-tabContent');
    var btntab_frame = document.getElementById('nav-tab');
    
    
    var formData = jsonString.replace(/\'{/g, '{').replace(/\}'/g, '}');
    var formDataObject = JSON.parse(formData);

    // for(var key in formDataObject){
    //     var elementData = JSON.parse(formDataObject[key]);
    //     console.log(elementData);
    //     var tab_Btn = `<li class="nav-item px-2 mb-2"><a class="btn btn-outline-primary active" style="width: 93px;" data-bs-toggle="tab" href="#activepills">Home</a></li>`
    //     btntab_frame.innerHTML += tab_Btn
    //     tab_frame.innerHTML += elementData

    // }
    btntab_frame.innerHTML = '';
    tab_frame.innerHTML = '';

    for (var key in formDataObject) {
        if (formDataObject.hasOwnProperty(key)) {
            var elementData = JSON.parse(formDataObject[key]);
            var tabContentId = 'tab-' + key;
            
            tab_frame.innerHTML += elementData;

            var idMatch = elementData.match(/id="([^"]+)"/);
            if (idMatch) {
                var idValue = idMatch[1];
                var tab_Btn = `
                    <li class="nav-item px-2 mb-2">
                        <a class="btn btn-outline-primary" data-bs-toggle="tab" href="#${idValue}">${key}</a>
                    </li>`;
                btntab_frame.innerHTML += tab_Btn;
            }
        }
    }
    var tab_list = {};
    $("#save").on("click", function () {
        var tab_content = document.getElementById('nav-tabContent').children;
        var tabBtn = document.getElementById('nav-tab').children;

        for (var tab_i = 0; tab_i < tabBtn.length; tab_i++) {
            console.log(tabBtn[tab_i].textContent);
        }

        newId = 0;
        for(var i = 0 ; i<tab_content.length; i++){
            tab_name = tabBtn[i].textContent;
            
            
            var formChildAttributes = tab_content[i].children;
            for(let element=0; element < formChildAttributes.length; element++) {
                var col_id = formChildAttributes[element].firstChild.lastChild.previousSibling.id;
                var val = document.getElementById(col_id).value
                console.log(val)
                if(col_id){
                    var set_val = formChildAttributes[element].firstChild.lastChild.previousSibling
                    set_val.setAttribute("value", val);
                }
            }
            
            var formJSONString = JSON.stringify(tab_content[i].outerHTML);
            tab_list[tab_name]= formJSONString;
        }

        console.log(tab_list);

        var currentURL = window.location.href;

        var urlParts = currentURL.split('/');

        var urlID = urlParts[urlParts.length - 1];

        $.ajax({
            url: "{% url 'core:saveFormData' %}",
            type: "POST",
            data: {
                form_name: document.getElementById('form_name').textContent,
                tab_list: JSON.stringify(tab_list),
                uuId : urlID,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (data) {
                console.log(data);
                console.log("Data is successfully saved...");
            },
            error: function (data) {
                console.log("Something went wrong...");
            }
        });
    });

</script>

{% endblock extrajs %}

templates/core/publishForm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drag and Drop Example</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/core.css'%}">
    <link rel="stylesheet" href="{% static 'css/basic.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <span class="fs-5 d-none d-sm-inline">
                <h1 class="mb-0" style="color: #751721; font-family: 'Lucida Handwriting';"><b>Form Builder</b></h1>
            </span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll mx-2" style="--bs-scroll-height: 100px;">
                    
                </ul>
                
                {% if request.user.type == "STAFF" %}
                <a href="{% url 'account:staff-list' %}" class="btn btn-outline-primary fw-bold mx-2" style="border-radius: 50px;">User</a>
                <a href="{% url 'core:publish_form' %}" class="btn btn-outline-warning fw-bold mx-2" style="border-radius: 50px;">Published Form</a>
                <button class="btn btn-outline-info fw-bold" style="border-radius: 50px;" type="submit"
                    onclick="getHtmlContent()" data-bs-toggle="modal" data-bs-target="#code">Form Preview</button>
                <div class="dropdown mx-2">
                    <button class="btn btn-outline-dark dropdown-toggle" style="border-radius: 50px;" type="button"
                        id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        {{request.user.username}}
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Log Out</a></li>
                    </ul>
                </div>
                {% else %}
                <button class="btn btn-outline-primary fw-bold mx-2" style="border-radius: 50px;">User</button>
                <a href="{% url 'account:staff-list' %}" class="btn btn-outline-primary fw-bold mx-2" style="border-radius: 50px;">Staff</a>
                <a href="{% url 'core:publish_form' %}" class="btn btn-outline-warning fw-bold mx-2" style="border-radius: 50px;">Published Form</a>
                <button class="btn btn-outline-info fw-bold" style="border-radius: 50px;" type="submit"
                    onclick="getHtmlContent()" data-bs-toggle="modal" data-bs-target="#code">Form Preview</button>
                <div class="dropdown mx-2">
                    <button class="btn btn-outline-dark dropdown-toggle" style="border-radius: 50px;" type="button"
                        id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        {{request.user.username}}
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Log Out</a></li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container-fluid">    
        <div class="row flex-nowrap pt-2">
            <div class="text-center">
                <table class="table">
                    <thead>
                        <tr>
                            <th>User Name</th>
                            <th>UUID</th>
                            <th>Form Name</th>
                            <th>Form Link</th>
                            <th>Form QRCode</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for forms in form_data %}
                        <tr>
                            <td>{{forms.user}}</td>
                            <td>{{forms.form_uid}}</td>
                            <td>{{forms.form_name}}</td>
                            <td><a href="{{forms.form_link}}">{{forms.form_link}}</a></td>
                            <td><img src="data:image/png;base64,{{forms.form_qrcode}}" style="height: 100px; widht: 100px;"/></td>
                            {% comment %} <td>{{forms.attributes}}</td> {% endcomment %}
                            <td>
                                <a class="btn btn-sm btn-info" style="width: 100px;" href="{% url "account:staff-update" forms.id %}"> 
                                    <span class="fe fe-edit"> Edit</span> </a>
                                <a class="btn  btn-sm btn-danger" style="width: 100px;" href="{% url 'account:staff-delete' forms.id %}" onclick="return confirm('Are you sure you want to delete user?');">
                                    <span class="fe fe-trash-2">Delete</span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'js/form_builders.js' %}"></script>

</body>
</html>

templates/core/published_form.html
{% extends "base.html"%}

{% block title %}
Published Form List
{% endblock title %}

{% block content %}

<!-- PAGE-HEADER -->
<div class="page-header">
    <h1 class="page-title">Published Form</h1>
    {% comment %} <div>
        <a href="{% url 'account:user-add' %}" class="btn btn-primary label-btn">
            <i class="fe fe-plus label-btn-icon me-2"></i>
            ADD USER
        </a>
    </div> {% endcomment %}
</div>
<!-- PAGE-HEADER END -->

<!-- Row -->
<div class="row row-sm">
    <div class="col-lg-12">
        <div class="card">
            <!-- <div class="card-header" style="display: flex; justify-content: space-between;">
                <h3 class="card-title">List Of Staffs</h3>
                <a href="/" class="btn btn-primary label-btn">
                    <i class="fe fe-plus label-btn-icon me-2"></i>
                    ADD STAFF
                </a>
            </div> -->
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example2" class="table table-bordered text-nowrap border-bottom">
                        <thead>
                            <tr>
                                <th class="border-bottom-0">User Name</th>
                                {% comment %} <th class="border-bottom-0">UUID</th> {% endcomment %}
                                <th class="border-bottom-0">Form Name</th>
                                <th class="border-bottom-0">Form Link</th>
                                <th class="border-bottom-0">Form QRCode</th>
                                <th class="border-bottom-0">Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td>{{user.user}}</td>
                                {% comment %} <td>{{user.form_uid}}</td> {% endcomment %}
                                <td>{{user.form_name}}</td>
                                <td><a href="{{user.form_link}}">{{user.form_link}}</a></td>
                                <td class="text-center"><img src="data:image/png;base64,{{user.form_qrcode}}" style="height: 100px; width: 100px;"/></td>
                                {% comment %} <td>{{user.attributes}}</td> {% endcomment %}
                                <td class="text-center">
                                    {% comment %} <a class="btn btn-sm btn-info" style="width: 100px;" href=""> 
                                        <span class="fe fe-edit"> Edit</span> </a> {% endcomment %}
                                    <a class="btn  btn-sm btn-danger" style="width: 100px;" href="{% url "core:publishedform_delete" user.id %}" onclick="return confirm('Are you sure you want to delete form?');">
                                        <span class="fe fe-trash-2">Delete</span>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Row -->

{% endblock content %}