Form_Builder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Form_Builder import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('account.urls','accounts'),namespace='account')),
    path('core/', include(('core.urls','core'),namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    
    path('staff-list/',ListAllStaffView.as_view(), name='staff-list'),
    path('staff-add/',AddStaffView.as_view(), name='staff-add'),
    path('staff-update/<int:id>/',UpdateStaff.as_view(), name='staff-update'),
    path('staff-delete/<int:id>/',DeleteStaffPerson.as_view(), name='staff-delete'),
    
    path('user-list/',ListAllUserView.as_view(), name='user-list'),
    path('user-add/',AddUserView.as_view(), name='user-add'),
    path('user-update/<int:id>/',UpdateUserView.as_view(), name='user-update'),
    path('user-delete/<int:id>/',DeleteUserPerson.as_view(), name='user-delete'),
    
    path('company-list/', CompanyListView.as_view(), name="company-list"),
    path('company-add/', AddCompanyView.as_view(), name="company-add"),
    path('company-update/<int:id>/', UpdateCompanyView.as_view(), name="company-update"),
    path('company-delete/<int:id>/',DeleteCompany.as_view(), name='company-delete'),
    # path('companypanel/',CompanypanelView.as_view(), name='companypanel'),
    path('update-status-approve/<int:id>/',UpdateStatusApproveView, name='update-status-approve'),
    path('update-status-reject/<int:id>/',UpdateStatusRejectView, name='update-status-reject'),
    path('company_register/', CompanyRegisterView.as_view(), name="company_register"),
    
    path("NotPageFound", NotPageFound ,name="NotPageFound"),
] 

core/urls.py
from django.urls import path
from django.conf.urls.static import static
from Form_Builder import settings
from .views import *

urlpatterns = [
    path('', HomeView, name='home'),
    path('BuildForm/', BuildFormView, name='BuildForm'),
    path('saveForm/', saveForm, name='saveForm'),
    path('saveFormData/', saveFormData, name='saveFormData'),
    path('form/<str:form_uid>', generate_random_link, name='linkgenerator'),
    path('published_form/', PublishFormView.as_view(), name="published_form"),
    path('filledform_list/', FilledFormListView.as_view(), name="filledform_list"),
    path('publishedform_delete/<int:id>/', DeletePublishedForm.as_view(), name="publishedform_delete"),
    path('filledform_delete/<int:id>/', DeleteFilledForm.as_view(), name="filledform_delete"),
    
] 

templates/401.html
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords" content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="static/assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>Sash – Bootstrap 5 Admin & Dashboard Template</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="static/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
     <link href="static/assets/css/style.css" rel="stylesheet">

	<!-- Plugins CSS -->
    <link href="static/assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="static/assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="static/assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="static/assets/switcher/demo.css" rel="stylesheet">

</head>

<body class="login-img">

    <!-- BACKGROUND-IMAGE -->
    <div class="">

        <!-- GLOBAL-LOADER -->
        <div id="global-loader">
            <img src="static/assets/images/loader.svg" class="loader-img" alt="Loader">
        </div>
        <!-- End GLOBAL-LOADER -->

        <!-- PAGE -->
        <div class="page">
            <!-- PAGE-CONTENT OPEN -->
            <div class="page-content error-page error2  text-white">
                <div class="container text-center">
                    <div class="error-template">
                        <h1 class="display-1 mb-2">4<span class="custom-emoji"><svg xmlns="http://www.w3.org/2000/svg" height="140" width="140" data-name="Layer 1" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="#a2a1ff"/><path fill="#6563ff" d="M14.99951,17.0918a.99473.99473,0,0,1-.64209-.23438,3.766,3.766,0,0,0-4.71484,0,.99955.99955,0,1,1-1.28516-1.53125,5.81162,5.81162,0,0,1,7.28516,0,.99974.99974,0,0,1-.64307,1.76563Z"/><circle cx="15" cy="10" r="1" fill="#6563ff"/><circle cx="9" cy="10" r="1" fill="#6563ff"/></svg></span>1</h1>
                        <h5 class="error-details">
                            Sorry, an error has occured, Requested page not found!
                        </h5>
                        <div class="text-center">
                            <a class="btn btn-secondary mt-5 mb-5" onclick="history.back()"> <i class="fa fa-long-arrow-left"></i> Back </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- PAGE-CONTENT OPEN CLOSED -->
        </div>
        <!-- End PAGE -->

    </div>
    <!-- BACKGROUND-IMAGE -->

    <!-- JQUERY JS -->
    <script src="static/assets/js/jquery.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="static/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- Perfect SCROLLBAR JS-->
    <script src="static/assets/plugins/p-scroll/perfect-scrollbar.js"></script>

    <!-- Color Theme js -->
    <script src="static/assets/js/themeColors.js"></script>

    <!-- CUSTOM JS -->
    <script src="static/assets/js/custom.js"></script>

    <!-- Custom-switcher -->
    <script src="static/assets/js/custom-swicher.js"></script>

    <!-- Switcher js -->
    <script src="static/assets/switcher/js/switcher.js"></script>

</body>

</html>

templates/503.html
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
    <meta name="author" content="Spruko Technologies Private Limited">
    <meta name="keywords" content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="static/assets/images/brand/favicon.ico">

    <!-- TITLE -->
    <title>Sash – Bootstrap 5 Admin & Dashboard Template</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="static/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- STYLE CSS -->
     <link href="static/assets/css/style.css" rel="stylesheet">

	<!-- Plugins CSS -->
    <link href="static/assets/css/plugins.css" rel="stylesheet">

    <!--- FONT-ICONS CSS -->
    <link href="static/assets/css/icons.css" rel="stylesheet">

    <!-- INTERNAL Switcher css -->
    <link href="static/assets/switcher/css/switcher.css" rel="stylesheet">
    <link href="static/assets/switcher/demo.css" rel="stylesheet">

</head>

<body class="login-img">

    <!-- BACKGROUND-IMAGE -->
    <div class="">

        <!-- GLOBAL-LOADER -->
        <div id="global-loader">
            <img src="static/assets/images/loader.svg" class="loader-img" alt="Loader">
        </div>
        <!-- End GLOBAL-LOADER -->

        <!-- PAGE -->
        <div class="page">
            <!-- PAGE-CONTENT OPEN -->
            <div class="page-content error-page error2 text-white">
                <div class="container text-center">
                    <div class="error-template">
                        <h1 class="display-1 mb-2">5<span class="custom-emoji"><svg xmlns="http://www.w3.org/2000/svg" height="140" width="140" data-name="Layer 1" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="#a2a1ff"/><path fill="#6563ff" d="M12 17.0918a5.68094 5.68094 0 0 1-3.64258-1.3252 1.00029 1.00029 0 1 1 1.28516-1.5332 3.76085 3.76085 0 0 0 4.71484 0 1.00029 1.00029 0 0 1 1.28516 1.5332A5.68094 5.68094 0 0 1 12 17.0918zM16.91406 10.83594a.99676.99676 0 0 1-.707-.293 1.03323 1.03323 0 0 0-1.41406 0 .99989.99989 0 0 1-1.41406-1.41406 3.07249 3.07249 0 0 1 4.24218 0 1 1 0 0 1-.707 1.707z"/><circle cx="9" cy="10" r="1" fill="#6563ff"/></svg></span>3</h1>
                        <h5 class="error-details">
                            Sorry, an error has occured, Requested page not found!
                        </h5>
                        <div class="text-center">
                            <a class="btn btn-secondary mt-5 mb-5" onclick="history.back()"> <i class="fa fa-long-arrow-left"></i> Back </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- PAGE-CONTENT OPEN CLOSED -->
        </div>
        <!-- End PAGE -->

    </div>
    <!-- BACKGROUND-IMAGE -->

    <!-- JQUERY JS -->
    <script src="static/assets/js/jquery.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="static/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- Perfect SCROLLBAR JS-->
    <script src="static/assets/plugins/p-scroll/perfect-scrollbar.js"></script>

    <!-- Color Theme js -->
    <script src="static/assets/js/themeColors.js"></script>

    <!-- CUSTOM JS -->
    <script src="static/assets/js/custom.js"></script>

    <!-- Custom-switcher -->
    <script src="static/assets/js/custom-swicher.js"></script>

    <!-- Switcher js -->
    <script src="static/assets/switcher/js/switcher.js"></script>

</body>

</html>

templates/app-footer.html
<!-- FOOTER -->
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            {% comment %} <div class="col-md-12 col-sm-12 text-center">
                Copyright © <span id="year"></span> Designed with <span
                    class="fa fa-heart text-danger"></span> by  All rights reserved.
            </div> {% endcomment %}
        </div>
    </div>
</footer>
<!-- FOOTER END -->

templates/app-header.html
<!-- app-Header -->
<div class="app-header header sticky" onmousedown="return false">
    <div class="container-fluid main-container">
        <div class="d-flex">
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar" href="javascript:void(0)"></a>
            <!-- sidebar-toggle-->
            <a class="logo-horizontal " href="{% url "core:home" %}">
                {% comment %} <img src="/static/assets/images/brand/logo-white.png" class="header-brand-img desktop-logo" alt="logo">
                <img src="/static/assets/images/brand/logo-dark.png" class="header-brand-img light-logo1" alt="logo"> {% endcomment %}

                <h3 class="mb-0 header-brand-img desktop-logo text-center" style="color: #DEDEFC; font-family: 'papyrus';"><b>Form Builder</b></h3>
                <h3 class="mb-0 header-brand-img light-logo1 text-center" style="color: #6C5EFC; font-family: 'papyrus';"><b>Form Builder</b></h3>
            </a>
            <!-- LOGO -->
            <div class="main-header-center ms-3 d-none d-lg-block">
                
            </div>
            <div class="d-flex order-lg-2 ms-auto header-right-icons">
                <!-- SEARCH -->
                <button class="navbar-toggler navresponsive-toggler d-lg-none ms-auto" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4"
                    aria-controls="navbarSupportedContent-4" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fe fe-more-vertical"></span>
                </button>
                <div class="navbar navbar-collapse responsive-navbar p-0">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                        <div class="d-flex order-lg-2">
                            {% comment %} <div class="dropdown d-lg-none d-flex">
                                <a href="javascript:void(0)" class="nav-link icon" data-bs-toggle="dropdown">
                                    <i class="fe fe-search"></i>
                                </a>
                                <div class="dropdown-menu header-search dropdown-menu-start">
                                    <div class="input-group w-100 p-2">
                                        <input type="text" class="form-control" placeholder="Search....">
                                        <div class="input-group-text btn btn-primary">
                                            <i class="fa fa-search" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                </div>
                            </div> {% endcomment %}
                            
                            <!-- Theme-Layout Start -->
                            <div class="d-flex">
                                <a class="nav-link icon theme-layout nav-link-bg layout-setting">
                                    <span class="dark-layout"><i class="fe fe-moon"></i></span>
                                    <span class="light-layout"><i class="fe fe-sun"></i></span>
                                </a>
                            </div>
                            <!-- Theme-Layout End -->
                            
                            {% if request.user.is_authenticated %}
                            <div class="dropdown d-flex profile-1">
                                <a href="javascript:void(0)" data-bs-toggle="dropdown" class="nav-link leading-none d-flex">
                                    <img src="/static/assets/images/users/user.jpg" alt="profile-user"
                                        class="avatar  profile-user brround cover-image">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                    <div class="drop-heading">
                                        <div class="">
                                            <h4 class="text-dark mb-0 fs-14 fw-semibold">{{ request.user.username }}</h4>
                                            {% comment %} <small class="text-muted">{{ request.user.type }}</small> {% endcomment %}
                                        </div>
                                    </div>
                                    <div class="dropdown-divider m-0"></div>
                                    
                                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                                        <i class="dropdown-icon fe fe-alert-circle"></i> Sign out
                                    </a>
                                </div>
                            </div>
                            {% else %}
                            <button type="button" class="btn btn-pill btn-primary" data-bs-toggle="modal" data-bs-target="#input-modal" data-bs-whatever="@mdo"><i class="fa fa-sign-in me-2"></i>Sign In</button>

                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /app-Header -->

templates/app-sidebar.html
<!--APP-SIDEBAR-->
<div class="sticky" onmousedown="return false">
    <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
    <div class="app-sidebar">
        <div class="side-header p-0">
            <a class="header-brand1" href="{% url "core:home" %}">
                {% comment %} <img src="/static/assets/images/brand/logo-white.png" class="header-brand-img desktop-logo" alt="logo">
                <img src="/static/assets/images/brand/icon-white.png" class="header-brand-img toggle-logo" alt="logo"> {% endcomment %}
                {% comment %} <img src="/static/assets/images/brand/icon-dark.png" class="header-brand-img light-logo" alt="logo">
                <img src="/static/assets/images/brand/logo-dark.png" class="header-brand-img light-logo1" alt="logo"> {% endcomment %}
                <h1 class="mb-0 header-brand-img desktop-logo" style="color: #DEDEFC; font-family: 'papyrus';"><b>Form Builder</b></h1>
                <h4 class="header-brand-img toggle-logo" style="color: #DEDEFC; font-family: 'papyrus';"><b>Form Builder</b></h4>
                <h4 class="header-brand-img light-logo" style="color: #6C5EFC; font-family: 'papyrus';"><b>Form Builder</b></h4>
                <h1 class="mb-0 header-brand-img light-logo1" style="color: #6C5EFC; font-family: 'papyrus';"><b>Form Builder</b></h1>
            </a>
            <!-- LOGO -->
        </div>
        <div class="main-sidemenu">
            <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg"
                    fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                </svg></div>


            <!-- For Superuser Start -->
            {% if user.is_superuser %} 
            <ul class="side-menu">
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:home" %}">
                        <i class="side-menu__icon fe fe-home"></i>
                        <span class="side-menu__label">Dashboard</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:BuildForm" %}">
                        <i class="side-menu__icon fe fe-file-text"></i>
                        <span class="side-menu__label">Build Form</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:published_form" %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Form List</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:filledform_list' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Filled Form</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:company-list' %}">
                        <i class="side-menu__icon fe fe-briefcase"></i>
                        <span class="side-menu__label">Company</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:staff-list' %}">
                        <i class="side-menu__icon fe fe-user-check"></i>
                        <span class="side-menu__label">Staff</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:user-list' %}">
                        <i class="side-menu__icon fe fe-users"></i>
                        <span class="side-menu__label">User</span>
                    </a>
                </li>         
            </ul>
            {% endif %}  
            <!-- For Superuser End -->

            <!-- For Company Start -->
            {% if user.type == "COMPANY" %} 
            <ul class="side-menu">
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:home" %}">
                        <i class="side-menu__icon fe fe-home"></i>
                        <span class="side-menu__label">Dashboard</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:BuildForm" %}">
                        <i class="side-menu__icon fe fe-file-text"></i>
                        <span class="side-menu__label">Build Form</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:published_form' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Form List</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:filledform_list' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Filled Form</span>
                    </a>
                </li>    
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:staff-list' %}">
                        <i class="side-menu__icon fe fe-user-check"></i>
                        <span class="side-menu__label">Staff</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:user-list' %}">
                        <i class="side-menu__icon fe fe-users"></i>
                        <span class="side-menu__label">User</span>
                    </a>
                </li>         
            </ul>
            {% endif %}  
            <!-- For Company End -->

            <!-- For Staff Start -->
            {% if user.type == "STAFF" %}
            <ul class="side-menu">
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:home" %}">
                        <i class="side-menu__icon fe fe-home"></i>
                        <span class="side-menu__label">Dashboard</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:BuildForm" %}">
                        <i class="side-menu__icon fe fe-file-text"></i>
                        <span class="side-menu__label">Build Form</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:published_form' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Form List</span>
                    </a>
                </li>
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:filledform_list' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Filled Form</span>
                    </a>
                </li>    
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'account:user-list' %}">
                        <i class="side-menu__icon fe fe-users"></i>
                        <span class="side-menu__label">User</span>
                    </a>
                </li>         
            </ul>
            {% endif %}
            <!-- For Staff End -->

            <!-- For User Start -->
            {% if user.type == "USER" %}
            <ul class="side-menu">
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url "core:home" %}">
                        <i class="side-menu__icon fe fe-home"></i>
                        <span class="side-menu__label">Dashboard</span>
                    </a>
                </li> 
                <li class="slide">
                    <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'core:filledform_list' %}">
                        <i class="side-menu__icon fe fe-grid"></i>
                        <span class="side-menu__label">Filled Form</span>
                    </a>
                </li>     
            </ul>
            {% endif %}
            <!-- For User End -->


            <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191"
                    width="24" height="24" viewBox="0 0 24 24">
                    <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                </svg></div>
        </div>
    </div>
</div>
<!--/APP-SIDEBAR-->